Courseplay/Courseplay_FS25

translations/translation_tr.xml
Hi,
Like the translation i sent for fs22 version, made some edits and adapted it to fs25. 
Thanks for this great mod.
=> Update for Turkish translation

scripts/ai/jobs/CpAIJob.lua
=> Add try functions and callstacks for #65

scripts/specializations/CpAIWorker.lua
=> small adjustment

scripts/gui/hud/CpBaseHud.lua, scripts/specializations/CpCourseManager.lua, scripts/specializations/CpHud.lua
=> Fixed some leftover hud zoom code

scripts/ai/turns/TurnContext.lua, scripts/ai/turns/TurnManeuver.lua
May also fix #93, which is a problematic course as the implement is very wide compared to the field.
=> fix: turn maneuver calculation

config/gui/pages/CourseGeneratorFrame.xml, scripts/field/CustomFieldManager.lua, scripts/gui/CpInGameMenu.lua, scripts/gui/pages/CpCourseGeneratorFrame.lua, scripts/gui/pages/CpGlobalSettingsFrame.lua, scripts/gui/pages/CpVehicleSettingsFrame.lua, scripts/specializations/CpHud.lua
=> Hud keybind change to close the hud and custom field hotspot

Courseplay.lua, scripts/CpGlobalSettings.lua, scripts/debug/CpDebug.lua, scripts/specializations/CpHud.lua
=> Might fix f1 menu keybinds #91

scripts/specializations/CpCourseManager.lua
Can't reproduce this, check added.
#122
=> fix: nil check

scripts/ai/util/AIUtil.lua
=> Try / catch for possible broken Giants function ..

scripts/ai/controllers/FertilizingSowingMachineController.lua
=> Might fix #156

config/MasterTranslations.xml, modDesc.xml, scripts/specializations/CpAIWorker.lua, translations/translation_br.xml, translations/translation_cs.xml, translations/translation_ct.xml, translations/translation_cz.xml, translations/translation_da.xml, translations/translation_de.xml, translations/translation_ea.xml, translations/translation_en.xml, translations/translation_es.xml, translations/translation_fc.xml, translations/translation_fi.xml, translations/translation_fr.xml, translations/translation_hu.xml, translations/translation_it.xml, translations/translation_jp.xml, translations/translation_kr.xml, translations/translation_nl.xml, translations/translation_no.xml, translations/translation_pl.xml, translations/translation_pt.xml, translations/translation_ro.xml, translations/translation_ru.xml, translations/translation_sv.xml, translations/translation_tr.xml
#147 
- Test:
- Check all vehicle action event, if they are still working correctly.
=> Add Keybinds to directly start at first/nearest or last waypoint

scripts/ai/turns/TurnManeuver.lua
Fix analytic path parameter order
#187
=> fix: Vine turns

Courseplay.lua, modDesc.xml, scripts/ai/strategies/AIDriveStrategyBunkerSilo.lua, scripts/silo/BunkerSiloVehicleController.lua, scripts/silo/BunkerSiloWrapper.lua, scripts/specializations/CpAIBunkerSiloWorker.lua, scripts/specializations/CpAIImplement.lua, scripts/specializations/CpAISiloLoaderWorker.lua
#174 and #169
- Also added Cp AI Implement Spec for future use
- Test:
- Starting one normal shovel loader
- The vehicles mentioned in the issues
=> Fixes for #174 and #169

scripts/gui/CpInGameMenu.lua, scripts/gui/CustomFieldHotspot.lua, scripts/gui/pages/CpCourseGeneratorFrame.lua, scripts/gui/pages/CpHelpFrame.lua
- Test custom field hotspots in the cp ingame menu
- Check page icons
=> Gui additions

scripts/ai/controllers/BaleLoaderController.lua
=> Fix for #243

scripts/ai/controllers/BalerController.lua
=> Fix for cotton harvesters #133

config/DebugChannels.xml, scripts/ai/controllers/FoldableController.lua, scripts/ai/jobs/CpAIJob.lua, scripts/ai/strategies/AIDriveStrategyDriveToFieldWorkStart.lua, scripts/specializations/CpAIWorker.lua
=> Fix for #234 and helper limit fix

scripts/CpUtil.lua
Added forgotten parameter ...
#302
=> fix: vehicle debug flag check

scripts/ai/jobs/CpAIJobBaleFinder.lua, scripts/specializations/CpAIFieldWorker.lua
=> Added nil check

scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
=> fix: yet another division by zero

scripts/CpObject.lua
Test if the onCpFull Event is called, when CP is full
=> Bug fix with giants class interaction

config/VehicleConfigurations.xml, scripts/ai/controllers/PipeController.lua, scripts/ai/controllers/ShovelController.lua, scripts/ai/controllers/TrailerController.lua, scripts/ai/strategies/AIDriveStrategyCombineCourse.lua, scripts/ai/strategies/AIDriveStrategyUnloadCombine.lua
Should test unloading different harvesters in different scenarios, like end of row, pocket, moving, stopped, etc.
=> 240 nach abtanken von spinaternter abfahrer fährt nicht weg und somit fährt der ernter nicht weiter

scripts/Course.lua, scripts/ai/jobs/CpAIJob.lua, scripts/ai/jobs/CpJobParameters.lua, scripts/ai/parameters/AIParameterSettingList.lua, scripts/specializations/CpCourseGeneratorSettings.lua, scripts/specializations/CpVehicleSettings.lua
- Should fix #273
- Removed invalid event calls
=> Diff MP fixes

scripts/gui/pages/CpCourseManagerFrame.lua
=> Added nil check for #363

scripts/courseGenerator/FieldworkCourse.lua
Fix first headland width when there is more than
one headland with round corners.
=> fix: first headland width

scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
=> fix: divide by zero

scripts/ai/util/ImplementUtil.lua
=> fix: fake AI marker width for balers

scripts/ai/util/AIUtil.lua
Looks like Giants now can return nils for just
about anything...
=> fix: AI agent size check

scripts/gui/pages/CpCourseGeneratorFrame.lua
=> Fix for #392

scripts/ai/util/WorkWidthUtil.lua
Left is negative, right is positive for Giants, our internal representation is the opposite.
=> fix: Giants tool side offset

scripts/specializations/CpAICombineUnloader.lua, scripts/specializations/CpVehicleSettings.lua
=> Fix for issue #378

scripts/gui/pages/CpCourseGeneratorFrame.lua
=> Might help with #361

scripts/gui/pages/CpCourseGeneratorFrame.lua
=> Readded custom field size display

scripts/gui/pages/CpCourseGeneratorFrame.lua
=> Added nil check for hotspot

modDesc.xml, scripts/pathfinder/AStar.lua, scripts/pathfinder/HybridAStar.lua, scripts/pathfinder/HybridAStarWithAStarInTheMiddle.lua, scripts/pathfinder/PathfinderUtil.lua, scripts/pathfinder/State3D.lua
Mainly refactoring the pathfinder code into multiple files. 
Improved post-smoothing to avoid "drunk-driving" on long straight paths.
=> Pathfinder refactoring/improvements

scripts/gui/pages/CpCourseGeneratorFrame.lua
=> fix: CP menu while job is running

scripts/ai/jobs/CpJobParameters.lua
=> Another stupid fix from leftover fs 22 code ..

scripts/ai/SelfUnloadHelper.lua, scripts/ai/jobs/CpAIJobCombineUnloader.lua, scripts/ai/strategies/AIDriveStrategyFindBales.lua, scripts/ai/strategies/AIDriveStrategyUnloadCombine.lua, scripts/courseGenerator/geometry/LineSegment.lua, scripts/courseGenerator/test/LineSegmentTest.lua, scripts/test/CpMathUtilTest.lua, scripts/util/CpMathUtil.lua
Fix point to polygon distance calculation.
Test self unload (unloader and combine) and bale finder.
=> Trailer search fix

modDesc.xml, scripts/Logger.lua, scripts/ai/strategies/AIDriveStrategyFieldWorkCourse.lua, scripts/ai/turns/AITurn.lua, scripts/ai/turns/WorkEndHandler.lua, scripts/ai/turns/WorkStartHandler.lua
Refactored the whole raise/lower logic.
=> feat: raise/lower each tool individually

scripts/gui/pages/CpCourseGeneratorFrame.lua
https://github.com/Courseplay/Courseplay_FS25/issues/572#issuecomment-2662935714
=> Adds nil check for none cp jobs

Courseplay.lua, scripts/CpUtil.lua
=> Removes all cp event listeners in the shop config

scripts/ai/jobs/CpAIJob.lua, scripts/specializations/CpCourseGenerator.lua
#534
Tries to synchronize the custom field correctly.
=> Might help with #534

Courseplay.lua
=> Reactivated drawing the field course on the hud

modDesc.xml, scripts/ai/jobs/CpAIJob.lua, scripts/events/FieldPolygonChangedEvent.lua, scripts/specializations/CpCourseGenerator.lua
=> Added fieldpolygon event

scripts/courseGenerator/Field.lua, scripts/courseGenerator/FieldworkCourseHelper.lua, scripts/courseGenerator/test/PolygonTest.lua, scripts/field/CpFieldUtil.lua, scripts/field/FieldBoundaryDetector.lua, scripts/geometry/Polygon.lua, scripts/gui/plots/CoursePlot.lua, scripts/gui/plots/FieldPlot.lua
=> Fix Giants field boundary detection issues

scripts/ai/jobs/CpAIJobCombineUnloader.lua
=> fix: remove obsolete check from unloader start

scripts/pathfinder/AStar.lua
=> fix: cache penalties for A* post-smoothing

scripts/courseGenerator/test/PolygonTest.lua, scripts/geometry/Polygon.lua
Fix index rollover from the last to the first vertex.
=> fix: self intersection detection

scripts/ai/turns/WorkEndHandler.lua, scripts/ai/turns/WorkStartHandler.lua
=> fix: Logger constructor parameters

scripts/specializations/CpHud.lua
#651
- Test if the cp hud is still being drawn
=> Changed hud onDraw to onDrawUIInfo

scripts/Logger.lua, scripts/ai/turns/WorkEndHandler.lua, scripts/ai/turns/WorkStartHandler.lua
Also fixed Logger.debugSparse()
=> fix: work start/end handler logging

scripts/ai/FieldWorkerProximityController.lua, scripts/courseGenerator/CourseGeneratorInterface.lua
=> Issues 685 691

scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
=> refactor: check for AD unloader when stopped for unload

scripts/ai/PurePursuitController.lua, scripts/ai/strategies/AIDriveStrategyUnloadCombine.lua
=> fix: disable off-track detection when following chopper

Courseplay.lua
#652
Test:
- Join MP game as client change hud position 
- Quit game check logs for erros and rejoin game
=> Might help with #652

scripts/field/CustomField.lua
=> Fix for #726

scripts/courseGenerator/RowPattern.lua
=> fix: add missing entries for lands pattern

scripts/ai/turns/AITurn.lua
=> fix: CCW combine turns

scripts/editor/CourseEditor.lua
=> Fix for course editor lane offset

scripts/ai/turns/TurnManeuver.lua
=> fix: harvester headland turn tuning

scripts/specializations/CpCourseGenerator.lua, scripts/specializations/CpCourseGeneratorSettings.lua, scripts/specializations/CpCourseManager.lua
=> fix: specialization race conditions
