- config/VehicleConfigurations.xml
- scripts/Course.lua
- scripts/Waypoint.lua
- scripts/ai/AIDriveStrategyBunkerSilo.lua
- scripts/ai/AIDriveStrategyFieldWorkCourse.lua
- scripts/ai/AIDriveStrategyUnloadCombine.lua
- scripts/ai/AIUtil.lua
- scripts/ai/turns/AITurn.lua
- scripts/ai/turns/TurnContext.lua
- scripts/ai/turns/TurnManeuver.lua
- scripts/pathfinder/PathfinderUtil.lua
- scripts/specializations/CpCourseManager.lua
The Prios 440 needs a implementWheelAlwaysOnGround configuration, but otherwise looks good.
> Turns again

- scripts/ai/turns/AITurn.lua
Back up less with implements on front in headland
turns.
> Headland turn

- .github/ISSUE_TEMPLATE/BUG_REPORT_DE.yml
- .github/ISSUE_TEMPLATE/BUG_REPORT_EN.yml
- .github/ISSUE_TEMPLATE/QUESTION_DE.yml
- .github/ISSUE_TEMPLATE/QUESTION_EN.yml
- .github/ISSUE_TEMPLATE/REQUEST_DE.yml
- .github/ISSUE_TEMPLATE/REQUEST_EN.yml
- Courseplay.lua
- config/MasterTranslations.xml
- config/VehicleConfigurations.xml
- modDesc.xml
- scripts/Course.lua
- scripts/ai/AIDriveStrategyAttachHeader.lua
- scripts/ai/AIDriveStrategyCourse.lua
- scripts/ai/AIDriveStrategyDriveToFieldWorkStart.lua
- scripts/ai/AIDriveStrategyFieldWorkCourse.lua
- scripts/ai/AIDriveStrategyShovelSiloLoader.lua
- scripts/ai/AIDriveStrategyUnloadCombine.lua
- scripts/ai/AIDriveStrategyVineFieldWorkCourse.lua
- scripts/ai/CollisionAvoidanceController.lua
- scripts/ai/PathfinderController.lua
- scripts/ai/ProximitySensor.lua
- scripts/ai/SelfUnloadHelper.lua
- scripts/courseGenerator/genetic/BlockSequencer.lua
- scripts/courseGenerator/genetic/Genetic.lua
- scripts/gui/FieldPlot.lua
- scripts/pathfinder/PathfinderConstraints.lua
- scripts/pathfinder/PathfinderContext.lua
- scripts/pathfinder/PathfinderUtil.lua
- translations/translation_de.xml
- translations/translation_en.xml
Might be more to do then just this, but this was abvious.
> Help menu revisit

- scripts/specializations/CpHud.lua
- While AD Hud is active, closing of the cp hud is only possible with the mouse, if the mouse is hovering over the CP Hud.
- CP is no longer blocking the AD right mouse button event
> Adjustment to the hud open/close mouse keybind

- scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
AutoDrive now only tells us to open the pipe when
it has already designated our harvester as the target so hopefully no more unnecessary pipe opening anymore.
> chore: reverting e24f80c9b62cfaa0f10429b8ed4136598239ee80

- scripts/geometry/Vector.lua
- scripts/util/CpMathUtil.lua
> fix: some more division by zero errors

- scripts/Course.lua
- scripts/ai/CollisionAvoidanceController.lua
- scripts/ai/turns/TurnManeuver.lua
The division by zero errors should now be fixed.
Was not able to reproduce the problem with the savegame attached to the issue. 
There is definitely a problem with the DeWulf PK3 Profi pipe being too low after a turn and the unloader using the pathfinder has a collision with the pipe.
> 80 combine mode fails with no path after one run

- scripts/CpUtil.lua
- scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
- scripts/dev/DevHelper.lua
- scripts/pathfinder/PathfinderUtil.lua
Removed PLACEMENT_BLOCKING which was added to avoid the rice field pumps, but was causing conflicts near other placeables and at random places, even on the middle of some fields, for whatever reason. Added STATIC_OBJECT instead, and also WATER, hoping that rice fields won't
trigger it.
> fix: collision flags changed

- scripts/ai/controllers/CutterController.lua
- scripts/dev/DevHelper.lua
Dirty hack to get rid of the error:
Cutter.lua:1494: invalid argument #1 to 'ipairs' (table expected, got nil) Seems like pickups aren't properly implemented for AI work.
Also included a DevHelper improvement.
#60
> fix: pickups

- scripts/ai/strategies/AIDriveStrategyFieldWorkCourse.lua
- scripts/dev/DevHelper.lua
- scripts/pathfinder/PathfinderConstraints.lua
- scripts/pathfinder/PathfinderContext.lua
- scripts/pathfinder/PathfinderUtil.lua
Make sure implements are lowered after the connecting path ends, even when the pathfinder fails.
This does not fix the fundamental problem of the pathfinder now failing more often, apparently colliding with AABBs which it should not according to the overlapBox() documentation.
#79
> fix: headland/center transition

- scripts/ai/controllers/PipeController.lua
- scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
This is to prevent some harvesters driving off once discharging finished with the bunker up, as that will result in leaving the area unharvested.
Also fix fruit detection for choppers so unloaders are directed to the correct side.
#176
> fix: Don't drive with pipe in not allowed states

- scripts/ai/tasks/CpAITaskFieldWork.lua
Avoids createting giants field strategies and deleting them directly after starting cp.
- Test:
- Test starting/stopping of a few different fieldwork combis
> Fix for #159

- scripts/dev/DevHelper.lua
- scripts/field/CpFieldUtil.lua
No idea why we even introduced the special rice field scanning, rice fields now seem to work just as any other field.
Add Left-Alt-C shortcut to devhelper to scan field.
> fix: disable special rice field scanning

- scripts/courseGenerator/FieldworkCourseMultiVehicle.lua
- scripts/geometry/Vector.lua
> fix: multi vehicle course with no headland

- scripts/specializations/CpCourseManager.lua
#215, #279
- The course display gets deleted and all nodes are set free before onLeave is called onDelete ...
- This also should fix the root cause and not the symptom from the PR #251
> Fixes use after free bug #215

- scripts/pathfinder/HybridAStar.lua
- scripts/pathfinder/PathfinderUtil.lua
Added safe getter for the highest distance.
Raised hybrid A* range from 3 radius to 6, direct
hybrid A* is fast enough, so this way we won't end up with a very short middle path (which caused the issue in the first place)
#301
> fix: pathfinder turn on headland

- config/jobParameters/FieldWorkJobParameterSetup.xml
- scripts/CpSettingsUtil.lua
- scripts/ai/jobs/CpJobParameters.lua
- scripts/ai/parameters/AIParameterSetting.lua
- scripts/gui/pages/CpCourseGeneratorFrame.lua
Test:
- change lane offset selection with the hud and gui
- simple mp test
#375
> Changed the lane offset setting logic

- scripts/Course.lua
Do not try doing a headland turn if the next
waypoint is on a connecting path.
> fix: headland turn

- scripts/gui/pages/CpCourseGeneratorFrame.lua
Commented out the now missing aiSystem:getJobByIndex() we don't need it for anything critical, just cosmetics.
#433
> workaround: 1.5 patch

- scripts/ai/strategies/AIDriveStrategyUnloadCombine.lua
- scripts/util/CpMathUtil.lua
#475 - when the combine asks for an unloader, the
unloader may not yet have the field polygon.
No idea if this was the problem only, or there is a multiplayer specific problem here too.
#456 - point to polygon distance fixed, so combine self unload, unloader start, baler start should not erroneously detect being too far from field.
> fix: unloader field polygon

- scripts/courseGenerator/Island.lua
Make sure island boundaries have vertices every few meters, even if the polygon has long straight edges.
Would also be possible to add waypoints to the generated course, as this really is a driving problem, not a generation problem, but the grassfire algorithm generating the headlands works better with more vertices.
> fix: island boundary vertices

- scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
Shouldn't falsely detect fruit on both sides, not
even with sugarbeet.
> fix: fruit check fixed

- scripts/specializations/CpAIFieldWorker.lua
- scripts/specializations/CpCourseManager.lua
We create a shortcut member (spec_cp<CP specialization name>) for the vehicle in the specialization's onLoad() function. It seems that sometimes there are other methods of the specialization are called before onLoad(), primarily when the vehicle is configured in the shop, so when these methods try to access the specialization through this shortcut, it is nil.
Introduce a function that returns the specialization, without using the shortcut and use that to access the specialization everywhere.
#655 #578 #586
> fix: possible specialization race condition

- scripts/ai/turns/TurnManeuver.lua
Make sure there is always a drivable reverse
section to the turn end after a turn was moved
back to fit on the field.
#609
> fix: stay on field turn maneuver

- scripts/ai/parameters/CpAIParameterUnloadingStation.lua
- scripts/gui/pages/CpCourseGeneratorFrame.lua
> Fixes #733

- scripts/ai/turns/AITurn.lua
- scripts/ai/turns/WorkStartHandler.lua
Rotate the plow before attempting to lower it.
No change to the row ending. Contrary to what the issue says, row ending is the same now as it was before the change for independent implement raise/lowering.
> fix: row start with plow

- scripts/ai/strategies/AIDriveStrategyFieldWorkCourse.lua
Fix a rare race condition where the PPC still had the finish row course while the pathfinder was working on the connecting path.
The PPC called the strategy's listeners with the finish row course waypoint index, which was interpreted by the listener as a main fieldwork course waypoint, leading to start a headland turn already passed.
#735
> fix: connecting path transition

- scripts/specializations/CpVehicleSettings.lua
> Fix max speed calculation

- scripts/ai/strategies/AIDriveStrategyUnloadCombine.lua
Be more tolerant when aligning with a moving combine so we don't try to fix our position prematurely.
> feat: unloader alignment to moving combine

- scripts/ai/tasks/CpAITaskFieldWork.lua
Make sure onAIFieldWorkerStart is triggered both on the client and the server, but on the server, trigger earlier.
#818
> fix: send fieldworker start event

- scripts/ai/controllers/CombineController.lua
- scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
At many harvesters, especially potato and other
root vegetable harvesters, the fruit needs a long
time to get from the ground to the tank.
This means there's a significant amount of fruit
harvested but not showing up in the tank's fill
level.
Add all fruit already harvested to the fill level
so we stop the moment enough fruit is harvested to reach 100%.
#357
> fix: fill level for harvesters

- config/VehicleConfigurations.xml
- scripts/Course.lua
- scripts/CpUtil.lua
- scripts/ai/controllers/CombineController.lua
- scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
- scripts/ai/turns/AITurn.lua
- scripts/ai/turns/TurnContext.lua
- scripts/ai/turns/TurnManeuver.lua
Use a Reeds-Shepp turn instead of the old combine
headland turn which used angles and relative
distances to steer the vehicle.
> 786 oxbo pea harvester headland turn

- scripts/specializations/CpVehicleSettings.lua
Detect pipe offset also when the auger wagon with the pipe is not directly attached to the tractor, such in case of the Annaburger AW 22.16, which is attached through the HTS 22B.79 platform.
#931
> fix: Pipe offset detection

- scripts/CpUtil.lua
- scripts/ai/Markers.lua
- scripts/ai/parameters/AIParameterSettingList.lua
- scripts/ai/strategies/AIDriveStrategyCombineCourse.lua
- scripts/courseGenerator/Headland.lua
Measuring the length of harvesters with raycast did not work as expected, because some, like the Oxbo is "transparent" at the default 1.5 m height.
Measure at multiple heights, also consider side offset for towed harvesters now. Measure every 10 seconds to account for a towed harvester at an angle when starting.
Should help with unloaders approaching the harvesters from further back.
#940
> fix: more robust harvester back measurement

- scripts/field/FieldBoundaryDetector.lua
Trigger successful field detection also when the callback is called with success == true, not only when the state changes to FINISHED, as apparently, the Giants field detector may get stuck in the FieldCourseDetectionState.ISLAND_DETECTION state even when finished successfully.
#1020
> fix: field detection

- scripts/field/CustomFieldManager.lua
Nil check when collecting the existing automatically named custom field numbers.
#1041
Rename a custom field to CP-number-number and then try creating a new one.
> fix: custom field numbers

- scripts/courseGenerator/FieldworkCourse.lua
Do not allow headlands that cross the outermost one as that means the tool will work outside the field boundary.
Also, outermost headland must not cross field boundary.
> fix: inner headlands must not cross outermost one
